
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(887, 632)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_edit = QtWidgets.QLineEdit(self.page)
        self.name_edit.setMinimumSize(QtCore.QSize(350, 0))
        self.name_edit.setObjectName("name_edit")
        self.verticalLayout.addWidget(self.name_edit)
        self.secondName_edit = QtWidgets.QLineEdit(self.page)
        self.secondName_edit.setObjectName("secondName_edit")
        self.verticalLayout.addWidget(self.secondName_edit)
        self.name_group = QtWidgets.QComboBox(self.page)
        self.name_group.setObjectName("name_group")
        self.verticalLayout.addWidget(self.name_group)
        self.generate = QtWidgets.QPushButton(self.page)
        self.generate.setObjectName("generate")
        self.verticalLayout.addWidget(self.generate)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gen_password = QtWidgets.QLineEdit(self.page)
        self.gen_password.setReadOnly(True)
        self.gen_password.setObjectName("gen_password")
        self.gridLayout_2.addWidget(self.gen_password, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gen_login = QtWidgets.QLineEdit(self.page)
        self.gen_login.setReadOnly(True)
        self.gen_login.setObjectName("gen_login")
        self.gridLayout_2.addWidget(self.gen_login, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.save = QtWidgets.QPushButton(self.page)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openDelete = QtWidgets.QPushButton(self.page)
        self.openDelete.setObjectName("openDelete")
        self.horizontalLayout_2.addWidget(self.openDelete)
        self.remind_student = QtWidgets.QPushButton(self.page)
        self.remind_student.setObjectName("remind_student")
        self.horizontalLayout_2.addWidget(self.remind_student)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.close_remind = QtWidgets.QPushButton(self.page_2)
        self.close_remind.setObjectName("close_remind")
        self.gridLayout_4.addWidget(self.close_remind, 6, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.page_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_remind = QtWidgets.QLineEdit(self.page_2)
        self.name_remind.setMinimumSize(QtCore.QSize(350, 0))
        self.name_remind.setObjectName("name_remind")
        self.verticalLayout_2.addWidget(self.name_remind)
        self.secondName_remind = QtWidgets.QLineEdit(self.page_2)
        self.secondName_remind.setObjectName("secondName_remind")
        self.verticalLayout_2.addWidget(self.secondName_remind)
        self.group_remind = QtWidgets.QComboBox(self.page_2)
        self.group_remind.setObjectName("group_remind")
        self.verticalLayout_2.addWidget(self.group_remind)
        self.remind = QtWidgets.QPushButton(self.page_2)
        self.remind.setObjectName("remind")
        self.verticalLayout_2.addWidget(self.remind)
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout_6.setHorizontalSpacing(10)
        self.gridLayout_6.setVerticalSpacing(14)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.old_login = QtWidgets.QLineEdit(self.page_2)
        self.old_login.setReadOnly(True)
        self.old_login.setObjectName("old_login")
        self.gridLayout_6.addWidget(self.old_login, 0, 1, 1, 1)
        self.old_password = QtWidgets.QLineEdit(self.page_2)
        self.old_password.setReadOnly(True)
        self.old_password.setObjectName("old_password")
        self.gridLayout_6.addWidget(self.old_password, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.name_delete = QtWidgets.QLineEdit(self.page_3)
        self.name_delete.setObjectName("name_delete")
        self.verticalLayout_3.addWidget(self.name_delete)
        self.secondName_delete = QtWidgets.QLineEdit(self.page_3)
        self.secondName_delete.setObjectName("secondName_delete")
        self.verticalLayout_3.addWidget(self.secondName_delete)
        self.group_delete = QtWidgets.QComboBox(self.page_3)
        self.group_delete.setObjectName("group_delete")
        self.verticalLayout_3.addWidget(self.group_delete)
        self.line_5 = QtWidgets.QFrame(self.page_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.deleteStudent = QtWidgets.QPushButton(self.page_3)
        self.deleteStudent.setObjectName("deleteStudent")
        self.verticalLayout_3.addWidget(self.deleteStudent)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 2, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem9, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 3, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 2, 2, 1, 1)
        self.go_back = QtWidgets.QPushButton(self.page_3)
        self.go_back.setObjectName("go_back")
        self.gridLayout_5.addWidget(self.go_back, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("LpForStudent", "LpForStudent"))
        self.name_edit.setPlaceholderText(_translate("Form", "Имя..."))
        self.secondName_edit.setPlaceholderText(_translate("Form", "Фамилия..."))
        self.generate.setText(_translate("Form", "Сгенерировать логин и пароль"))
        self.label.setText(_translate("Form", "Пароль:"))
        self.label_2.setText(_translate("Form", "Логин: "))
        self.save.setText(_translate("Form", "Сохранить"))
        self.openDelete.setText(_translate("Form", "Удалить пользователя"))
        self.remind_student.setText(_translate("Form", "Напомнить логин и пароль"))
        self.close_remind.setText(_translate("Form", "Вернуться назад"))
        self.name_remind.setPlaceholderText(_translate("Form", "Имя..."))
        self.secondName_remind.setPlaceholderText(_translate("Form", "Фамилия..."))
        self.remind.setText(_translate("Form", "Напомнить"))
        self.label_3.setText(_translate("Form", "Логин: "))
        self.label_4.setText(_translate("Form", "Пароль: "))
        self.label_5.setText(_translate("Form", "Напомнить логин и пароль"))
        self.name_delete.setPlaceholderText(_translate("Form", "Имя..."))
        self.secondName_delete.setPlaceholderText(_translate("Form", "Фамилия..."))
        self.deleteStudent.setText(_translate("Form", "Удалить"))
        self.label_6.setText(_translate("Form", "Удалить пользователя"))
        self.go_back.setText(_translate("Form", "Вернуться назад"))
